name: the_vision
description: ØªØ·Ø¨ÙŠÙ‚ Ù…ÙƒØªØ¨ Ø§Ù„Ø±Ø¤ÙŠØ© Ù„Ù„Ø¯Ø±Ø§Ø³Ø© ÙÙŠ Ø±ÙˆØ§Ù†Ø¯Ø§

publish_to: 'none'

version: 1.2.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  google_fonts: ^6.1.0
  share_plus: ^7.2.1

  # State Management & Providers
  provider: ^6.1.1
  shared_preferences: ^2.1.1
  
  # UI & Navigation
  smooth_page_indicator: ^2.0.1
  photo_view: ^0.15.0
  font_awesome_flutter: ^10.12.0
  
  # File & Media Handling
  file_picker: ^10.3.7
  image_picker: ^0.8.7
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.3.0
  
  # Networking & Communications
  url_launcher: ^6.3.2
  mailer: ^6.2.5
  http: ^1.2.2
  
  # Localization & Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # Connectivity
  connectivity_plus: ^4.0.2
  
  # Performance
  flutter_cache_manager: ^3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # ðŸ‘‡ Ù…ÙƒØªØ¨Ø© ØªÙˆÙ„ÙŠØ¯ Ø§Ù„Ø£ÙŠÙ‚ÙˆÙ†Ø§Øª
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    # âœ… Ø¥Ø¶Ø§ÙØ© Ù…Ù„Ù Ø§Ù„Ø¨ÙŠØ¦Ø© Ù„Ù„Ø£ØµÙˆÙ„
    - .env
    
    # Images
    - assets/images/
    - assets/images/The_Vision_P1.jpg
    - assets/images/The_Vision_P2.jpg
    - assets/images/In_Rwanda_1.jpg
    - assets/images/In_Rwanda_2.jpg
    - assets/images/In_Rwanda_3.jpg
    - assets/images/In_Rwanda_4.jpg
    - assets/images/In_Rwanda_5.jpg
    - assets/images/In_Rwanda_6.jpg
    - assets/images/In_Rwanda_7.jpg
    - assets/images/In_Rwanda_8.jpg
    - assets/images/In_Rwanda_9.jpg
    - assets/images/In_Rwanda_10.jpg
    
    # ULK University Images
    - assets/images/ULK_P1.webp
    - assets/images/ULK_P2.jpeg
    - assets/images/ULK_P3.jpg
    - assets/images/ULK_P4.jpg
    - assets/images/ULK_P5.jpg
    - assets/images/ULK_P6.jpg
    - assets/images/ULK_PL1.jpg
    - assets/images/ULK_PL2.jpg
    
    # UoK University Images
    - assets/images/UoK_P1.jpg
    - assets/images/UoK_P2.jpg
    - assets/images/UoK_P3.jpg
    - assets/images/UoK_P4.jpg
    - assets/images/UoK_P5.jpg
    
    # UNILAK University Images
    - assets/images/UNLAK_P1.jpg
    - assets/images/UNLAK_P2.jpg
    - assets/images/UNLAK_P3.jpg
    
    # INES University Images
    - assets/images/INES_P1.jpeg
    - assets/images/INES_P2.jpeg
    - assets/images/INES_P3.jpg
    
    # UR University Images
    - assets/images/UR_P1.jpeg
    - assets/images/UR_P2.jpeg
    - assets/images/UR_P4.jpg
    - assets/images/UR_P5.jpg
    - assets/images/UR_P6.jpg

# ðŸ‘‡ Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª ØªÙˆÙ„ÙŠØ¯ Ø§Ù„Ø£ÙŠÙ‚ÙˆÙ†Ø©
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png" # âš ï¸ ØªØ£ÙƒØ¯ Ù…Ù† ÙˆØ¶Ø¹ ØµÙˆØ±Ø© Ø§Ù„Ù„ÙˆØ¬Ùˆ Ø¨Ù‡Ø°Ø§ Ø§Ù„Ø§Ø³Ù…
  min_sdk_android: 21