name: the_vision
description: ØªØ·Ø¨ÙŠÙ‚ Ù…ÙƒØªØ¨ Ø§Ù„Ø±Ø¤ÙŠØ© Ù„Ù„Ø¯Ø±Ø§Ø³Ø© ÙÙŠ Ø±ÙˆØ§Ù†Ø¯Ø§

publish_to: 'none'

version: 1.2.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Utilities & Assets
  flutter_dotenv: ^6.0.0
  google_fonts: ^6.2.1
  share_plus: ^12.0.1
  path_provider: ^2.1.4 # Ø£Ø¶ÙØªÙ‡Ø§ Ù„Ùƒ Ù„Ø£Ù†Ù‡Ø§ Ø¶Ø±ÙˆØ±ÙŠØ© Ù„Ù„ØªØ¹Ø§Ù…Ù„ Ù…Ø¹ Ø§Ù„Ù…Ù„ÙØ§Øª ÙˆØ§Ù„ØµÙˆØ±

  # State Management & Providers
  provider: ^6.1.2
  shared_preferences: ^2.3.2

  # UI & Navigation
  smooth_page_indicator: ^2.0.1
  photo_view: ^0.15.0
  font_awesome_flutter: ^10.7.0

  # File & Media Handling
  file_picker: ^10.3.8
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  cached_network_image: ^3.4.1

  # Networking & Communications
  url_launcher: ^6.3.0
  mailer: ^6.0.0
  http: ^1.2.2

  # ðŸ”¥ Ù…ÙƒØªØ¨Ø§Øª Ø§Ù„ÙØ§ÙŠØ±Ø¨ÙŠØ³ ÙˆØ§Ù„Ù…ØµØ§Ø¯Ù‚Ø© (Ø£Ø­Ø¯Ø« Ø¥ØµØ¯Ø§Ø±Ø§Øª)
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Connectivity & Performance
  connectivity_plus: ^7.0.0
  flutter_cache_manager: ^3.4.1
  firebase_messaging: ^16.1.0
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21